### ISSUE TITLE
`cargo run --example modnet ` error

### ISSUE THREAD

**Issue by phial3** [pykeio/ort#316]
`cargo run --example modnet --features "load-dynamic,cuda,fetch-models,ndarray"`
error info:
```text
warning: unused import: `std::os::unix::ffi::OsStrExt`
 --> src/util.rs:4:5
  |
4 | use std::os::unix::ffi::OsStrExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `ort` (lib) generated 1 warning (run `cargo fix --lib -p ort` to apply 1 suggestion)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/examples/modnet`
thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:757:9:
Failed to initialize any backend! Wayland status: XdgRuntimeDirNotSet X11 status: XOpenDisplayFailed
stack backtrace:
   0:     0xaaaae08933b4 - std::backtrace_rs::backtrace::libunwind::trace::h478edc47103e3f06
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0xaaaae08933b4 - std::backtrace_rs::backtrace::trace_unsynchronized::h42581fa4d7d2711f
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0xaaaae08933b4 - std::sys::backtrace::_print_fmt::hfa792f5d727892f7
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:65:5
   3:     0xaaaae08933b4 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::hd1bd86f9e87f2dc6
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:40:26
   4:     0xaaaae08bb2ac - core::fmt::rt::Argument::fmt::h4994c882fc039333
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/rt.rs:173:76
   5:     0xaaaae08bb2ac - core::fmt::write::hf784ddce2439beb2
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/fmt/mod.rs:1182:21
   6:     0xaaaae088f780 - std::io::Write::write_fmt::h3a532ab2ed2a81ef
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/io/mod.rs:1827:15
   7:     0xaaaae0894798 - std::sys::backtrace::BacktraceLock::print::h3dc3d1eeb242dea4
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:43:9
   8:     0xaaaae0894798 - std::panicking::default_hook::{{closure}}::hdf566474624f0305
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:269:22
   9:     0xaaaae0894378 - std::panicking::default_hook::h7eca74c8246bec15
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:296:9
  10:     0xaaaae0894db0 - std::panicking::rust_panic_with_hook::h23f33ab5bab293ef
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:800:13
  11:     0xaaaae0894bb8 - std::panicking::begin_panic_handler::{{closure}}::h8ea86e6103cb361c
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:674:13
  12:     0xaaaae089389c - std::sys::backtrace::__rust_end_short_backtrace::h6e01bce97227982e
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:168:18
  13:     0xaaaae0894888 - rust_begin_unwind
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
  14:     0xaaaadf4ee6f0 - core::panicking::panic_fmt::hb1e0b874c9a3c491
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
  15:     0xaaaadf9153f4 - winit::platform_impl::platform::EventLoop<T>::new::h2ab3e05e95a0033e
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/platform_impl/linux/mod.rs:757:9
  16:     0xaaaadf914ab0 - winit::event_loop::EventLoopBuilder<T>::build::h6b111042f2357627
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/winit-0.28.7/src/event_loop.rs:121:25
  17:     0xaaaadf8e56b0 - show_image::backend::context::Context::new::h056cce845111e98d
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/show-image-0.14.0/src/backend/context.rs:174:20
  18:     0xaaaadf90e21c - show_image::backend::initialize_context::h8aa879a63233da81
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/show-image-0.14.0/src/backend/mod.rs:25:16
  19:     0xaaaadf90e3c4 - show_image::backend::initialize_context_or_exit::h31ded6b755de7dfc
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/show-image-0.14.0/src/backend/mod.rs:35:8
  20:     0xaaaadf4efbd0 - show_image::backend::run_context::hb1b31ed8255c6f0a
                               at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/show-image-0.14.0/src/backend/mod.rs:78:16
  21:     0xaaaadf4f20e8 - modnet::main::h5d93a5304de4621b
                               at /code/ort/examples/modnet/examples/modnet.rs:10:1
  22:     0xaaaadf5580b8 - core::ops::function::FnOnce::call_once::hf789c0c7c7016961
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
  23:     0xaaaadf514b34 - std::sys::backtrace::__rust_begin_short_backtrace::h371a02ee3b0e9fa9
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/backtrace.rs:152:18
  24:     0xaaaadf5c4e60 - std::rt::lang_start::{{closure}}::heafb4d3d6475a197
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:162:18
  25:     0xaaaae08882d0 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc83e0360677e1061
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:284:13
  26:     0xaaaae08882d0 - std::panicking::try::do_call::hcec7ace625a1aaf6
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  27:     0xaaaae08882d0 - std::panicking::try::h32c52e107e411c58
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  28:     0xaaaae08882d0 - std::panic::catch_unwind::hd88646b290a0ace7
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  29:     0xaaaae08882d0 - std::rt::lang_start_internal::{{closure}}::h2005ed25137ce85a
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:48
  30:     0xaaaae08882d0 - std::panicking::try::do_call::h471ef3d560f3540d
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:557:40
  31:     0xaaaae08882d0 - std::panicking::try::h81d64da2a2c5a1cf
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:521:19
  32:     0xaaaae08882d0 - std::panic::catch_unwind::ha54838b763989a8d
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panic.rs:350:14
  33:     0xaaaae08882d0 - std::rt::lang_start_internal::h69e5a956edcf8a00
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:141:20
  34:     0xaaaadf5c4e30 - std::rt::lang_start::h14f88f359070de11
                               at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/rt.rs:161:17
  35:     0xaaaadf4f2f88 - main
  36:     0xffffb10784c4 - <unknown>
  37:     0xffffb1078598 - __libc_start_main
  38:     0xaaaadf4ef030 - _start
  39:                0x0 - <unknown>
```

**Comment by decahedron1** [comment]
Seems there's a problem with your environment - the `XDG_RUNTIME_DIR` environment variable is not set. You could fix that, or just remove all references of `show_image` from the example and use [`Image::save`](https://docs.rs/image/latest/image/enum.DynamicImage.html#method.save) to save `output` to a file instead.
