### ISSUE TITLE
Windows `compile` build fails.

### ISSUE THREAD

**Issue by eublefar** [pykeio/ort#8]
Hi

I am trying to use your onnxruntime wrapper in my library. Ideally I'd like to build ort on windows with `compile` strategy and static linking.
I am running build from `Developer Command Prompt for VS 2019` as admin.

I am running build and test command 

`cargo build --features "directml" --features "prefer-compile-strategy" --features "compile-static"`
`cargo test  --features "directml" --features "prefer-compile-strategy" --features "compile-static"`

First it panics if clang is not installed 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', build.rs:495:138
```

But from the build script comments I think this is the small bug and instead your intention was to check if the clang and ninja are installed here:

```rust
// if we can use ninja on windows, great! let's use it!
// note that ninja + clang on windows is a total shitstorm so it's disabled for now
if Command::new("ninja").arg("--version").status().unwrap().success() && !Command::new("clang-cl").arg("--version").status().unwrap().success() {
...
```

So I just modify it to use ninja as cmake_generator and it fails with: `  fatal: No names found, cannot describe anything.`

Full trace:
```
error: failed to run custom build command for `ort v1.13.2 (D:\RustProjects\ort)`
Caused by:
  process didn't exit successfully: `D:\RustProjects\ort\target\debug\build\ort-53c3b3cbcbab5082\build-script-build` (exit code: 101)
  --- stdout
  [ort] strategy: "unknown"
  cargo:rerun-if-env-changed=ORT_STRATEGY
  Python 3.9.13
  [ort] assuming C/C++ compilers are available
  cargo:rerun-if-changed=D:\RustProjects\ort\target\debug\build\ort-976a8a4574b33aaa\out\protoc-3.11.2-win32.zip
  cargo:warning="C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.34.31933\\bin\\Hostx64\\x64"
  --- stderr
  2023-01-11 13:57:01,642 build [DEBUG] - Command line arguments:
    --build --update --parallel --skip_tests --skip_submodule_sync --config Debug --disable_rtti --disable_memleak_checker --enable_msvc_static_runtime --cmake_extra_defines onnxruntime_BUILD_UNIT_TESTS=0 --cmake_generator=Ninja --build_dir=build
  2023-01-11 13:57:01,917 build [INFO] - Build started
  2023-01-11 13:57:01,917 build [INFO] - Generating CMake build tree
  2023-01-11 13:57:01,917 util.run [INFO] - Running subprocess in 'build\Debug'
    'D:\Program Files\CMake\bin\cmake.EXE' 'D:\RustProjects\ort\target\debug\build\ort-976a8a4574b33aaa\out\onnxruntime\cmake' -Donnxruntime_RUN_ONNX_TESTS=OFF -Donnxruntime_GENERATE_TEST_REPORTS=ON '-DPython_EXECUTABLE=C:\Users\evil_unicorn\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' '-DPYTHON_EXECUTABLE=C:\Users\evil_unicorn\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -Donnxruntime_USE_MIMALLOC=OFF -Donnxruntime_ENABLE_PYTHON=OFF -Donnxruntime_BUILD_CSHARP=OFF -Donnxruntime_BUILD_JAVA=OFF -Donnxruntime_BUILD_NODEJS=OFF -Donnxruntime_BUILD_OBJC=OFF -Donnxruntime_BUILD_SHARED_LIB=OFF -Donnxruntime_BUILD_APPLE_FRAMEWORK=OFF -Donnxruntime_USE_DNNL=OFF -Donnxruntime_USE_NNAPI_BUILTIN=OFF -Donnxruntime_USE_RKNPU=OFF -Donnxruntime_USE_LLVM=OFF -Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF -Donnxruntime_USE_VITISAI=OFF -Donnxruntime_USE_TENSORRT=OFF -Donnxruntime_USE_TENSORRT_BUILTIN_PARSER=OFF -Donnxruntime_TENSORRT_PLACEHOLDER_BUILDER=OFF -Donnxruntime_USE_TVM=OFF -Donnxruntime_TVM_CUDA_RUNTIME=OFF -Donnxruntime_TVM_USE_HASH=OFF -Donnxruntime_USE_MIGRAPHX=OFF -Donnxruntime_CROSS_COMPILING=OFF -Donnxruntime_DISABLE_CONTRIB_OPS=OFF -Donnxruntime_DISABLE_ML_OPS=OFF -Donnxruntime_DISABLE_RTTI=ON -Donnxruntime_DISABLE_EXCEPTIONS=OFF -Donnxruntime_MINIMAL_BUILD=OFF -Donnxruntime_EXTENDED_MINIMAL_BUILD=OFF -Donnxruntime_MINIMAL_BUILD_CUSTOM_OPS=OFF -Donnxruntime_REDUCED_OPS_BUILD=OFF -Donnxruntime_ENABLE_LANGUAGE_INTEROP_OPS=OFF -Donnxruntime_USE_DML=OFF -Donnxruntime_USE_WINML=OFF -Donnxruntime_BUILD_MS_EXPERIMENTAL_OPS=OFF -Donnxruntime_USE_TELEMETRY=OFF -Donnxruntime_ENABLE_LTO=OFF -Donnxruntime_USE_ACL=OFF -Donnxruntime_USE_ACL_1902=OFF -Donnxruntime_USE_ACL_1905=OFF -Donnxruntime_USE_ACL_1908=OFF -Donnxruntime_USE_ACL_2002=OFF -Donnxruntime_USE_ARMNN=OFF -Donnxruntime_ARMNN_RELU_USE_CPU=ON -Donnxruntime_ARMNN_BN_USE_CPU=ON -Donnxruntime_ENABLE_NVTX_PROFILE=OFF -Donnxruntime_ENABLE_TRAINING=OFF -Donnxruntime_ENABLE_TRAINING_OPS=OFF -Donnxruntime_ENABLE_TRAINING_TORCH_INTEROP=OFF -Donnxruntime_ENABLE_TRAINING_ON_DEVICE=OFF -Donnxruntime_ENABLE_CPU_FP16_OPS=OFF -Donnxruntime_USE_NCCL=OFF -Donnxruntime_BUILD_BENCHMARKS=OFF -Donnxruntime_USE_ROCM=OFF -DOnnxruntime_GCOV_COVERAGE=OFF -Donnxruntime_USE_MPI=ON -Donnxruntime_ENABLE_MEMORY_PROFILE=OFF -Donnxruntime_ENABLE_CUDA_LINE_NUMBER_INFO=OFF -Donnxruntime_BUILD_WEBASSEMBLY=OFF -Donnxruntime_BUILD_WEBASSEMBLY_STATIC_LIB=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING=ON -Donnxruntime_ENABLE_WEBASSEMBLY_EXCEPTION_THROWING=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_THREADS=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_DEBUG_INFO=OFF -Donnxruntime_ENABLE_WEBASSEMBLY_PROFILING=OFF -Donnxruntime_ENABLE_EAGER_MODE=OFF -Donnxruntime_ENABLE_LAZY_TENSOR=OFF -Donnxruntime_ENABLE_EXTERNAL_CUSTOM_OP_SCHEMAS=OFF -Donnxruntime_ENABLE_CUDA_PROFILING=OFF -Donnxruntime_ENABLE_ROCM_PROFILING=OFF -Donnxruntime_USE_XNNPACK=OFF -Donnxruntime_USE_CANN=OFF -Donnxruntime_BUILD_UNIT_TESTS=0 -Donnxruntime_DEV_MODE=ON '-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>' -DONNX_USE_MSVC_STATIC_RUNTIME=ON -Dprotobuf_MSVC_STATIC_RUNTIME=ON -Dgtest_force_shared_crt=OFF -Donnxruntime_PYBIND_EXPORT_OPSCHEMA=OFF -G Ninja -Donnxruntime_ENABLE_MEMLEAK_CHECKER=OFF -DCMAKE_BUILD_TYPE=Debug
  Patch found: C:/Program Files/Git/usr/bin/patch.exe
  Use protobuf from submodule
  Use date from submodule
  Use mp11 from submodule
  Use json from submodule
  Use re2 from submodule
  Use cpuinfo from submodule
  Generated: D:/RustProjects/ort/target/debug/build/ort-976a8a4574b33aaa/out/onnxruntime/build/Debug/external/onnx/onnx/onnx-ml.proto
  Generated: D:/RustProjects/ort/target/debug/build/ort-976a8a4574b33aaa/out/onnxruntime/build/Debug/external/onnx/onnx/onnx-operators-ml.proto
  Generated: D:/RustProjects/ort/target/debug/build/ort-976a8a4574b33aaa/out/onnxruntime/build/Debug/external/onnx/onnx/onnx-data.proto
  Use flatbuffers from submodule
  fatal: No names found, cannot describe anything.
  CMake Warning (dev) at D:/Program Files/CMake/share/cmake-3.25/Modules/FetchContent.cmake:1279 (message):
    The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
    not set.  The policy's OLD behavior will be used.  When using a URL
    download, the timestamps of extracted files should preferably be that of
    the time of extraction, otherwise code that depends on the extracted
    contents might not be rebuilt if the URL changes.  The OLD behavior
    preserves the timestamps from the archive instead, but this is usually not
    what you want.  Update your project to the NEW behavior or specify the
    DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
    robustness issue.
  Call Stack (most recent call first):
    external/abseil-cpp.cmake:20 (FetchContent_Declare)
    onnxruntime_common.cmake:112 (include)
    CMakeLists.txt:2054 (include)
  This warning is for project developers.  Use -Wno-dev to suppress it.
  2023-01-11 13:57:06,106 util.run [DEBUG] - Subprocess completed. Return code: 0
  2023-01-11 13:57:06,106 build [INFO] - Building targets for Debug configuration
  2023-01-11 13:57:06,107 util.run [INFO] - Running subprocess in 'D:\RustProjects\ort\target\debug\build\ort-976a8a4574b33aaa\out\onnxruntime'
    'D:\Program Files\CMake\bin\cmake.EXE' --build 'build\Debug' --config Debug -- -j6
  Traceback (most recent call last):
    File "D:\RustProjects\ort\target\debug\build\ort-976a8a4574b33aaa\out\onnxruntime\tools\ci_build\build.py", line 2812, in <module>
      sys.exit(main())
    File "D:\RustProjects\ort\target\debug\build\ort-976a8a4574b33aaa\out\onnxruntime\tools\ci_build\build.py", line 2727, in main
      build_targets(args, cmake_path, build_dir, configs, num_parallel_jobs, args.target)
    File "D:\RustProjects\ort\target\debug\build\ort-976a8a4574b33aaa\out\onnxruntime\tools\ci_build\build.py", line 1349, in build_targets
      run_subprocess(cmd_args, env=env)
    File "D:\RustProjects\ort\target\debug\build\ort-976a8a4574b33aaa\out\onnxruntime\tools\ci_build\build.py", line 740, in run_subprocess
      return run(*args, cwd=cwd, capture_stdout=capture_stdout, shell=shell, env=my_env)
    File "D:\RustProjects\ort\target\debug\build\ort-976a8a4574b33aaa\out\onnxruntime\tools\python\util\run.py", line 49, in run
      completed_process = subprocess.run(
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 528, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['D:\\Program Files\\CMake\\bin\\cmake.EXE', '--build', 'build\\Debug', '--config', 'Debug', '--', '-j6']' returned non-zero exit status 1.
  thread 'main' panicked at 'failed to build ONNX Runtime', build.rs:518:13
  stack backtrace:
     0: std::panicking::begin_panic_handler
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\std\src\panicking.rs:575
     1: core::panicking::panic_fmt
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943/library\core\src\panicking.rs:65
     2: build_script_build::prepare_libort_dir
               at .\build.rs:518
     3: build_script_build::main
               at .\build.rs:597
     4: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
               at /rustc/69f9c33d71c871fc16ac445211281c6e7a340943\library\core\src\ops\function.rs:251
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
Process finished with exit code 101
```

And when using Visual Studio code generator build passes just fine, but when building tests I get a ton of `error LNK2001: unresolved external symbol `. Mostly names with `Dbg` and `protobuf` but there are also others.

All builds I tried were done after `clean`.

I need help because I am out of ideas.

**Comment by eublefar** [comment]
Installing LLVM with clang-cl leads to the same result as with just manually selecting visual studio in build.rs (as it does it anyway if clang is installed)

**Comment by sudo-carson** [comment]
With https://github.com/pykeio/ort/commit/27b673aae94ced572f11532c0e287abaad000264 I was able to compile ONNX Runtime successfully but ran into the same linking issues. Been trying to fix the linking errors for almost 6 hours now... I don't think static linking is supported in 1.13.2, Microsoft never really showed interest in supporting static linking anyways.

I'll keep trying (running into CRT linking errors now?), but the build is very slow even on my 5600X machine. In the mean time, you should build ONNX Runtime from source manually and use the `system` strategy to point to the binaries then.

**Comment by eublefar** [comment]
Thanks a lot for trying! I will it this way then
