### ISSUE TITLE
[DirectML] CreateSession failed

### ISSUE THREAD

**Issue by 18930215187** [pykeio/ort#94]
Error occured when using DirectML execution provider but cuda is fine. The information about error can't be shown in full.

version = "1.15.4", default-features = false, features = ["load-dynamic", "cuda", "tensorrt", "directml", "half"]

Output: 
```
2023-09-26T16:41:23.845811Z DEBUG ort::environment: Environment not yet initialized, creating a new one
2023-09-26T16:41:23.862108Z DEBUG ort::environment: Environment created env_ptr="0x148a05c2fc0"
2023-09-26T16:41:23.908269Z  INFO apply_execution_providers: ort::execution_providers: Successfully registered `DmlExecutionProvider`
2023-09-26T16:41:24.055449Z  INFO ort: Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-09-26T16:41:24.055466Z  INFO ort: Rerunning with verbose output on a non-minimal build will show node assignments.
2023-09-26T16:41:24.257247Z  WARN ort: Exception during initialization: 
2023-09-26T16:41:24.292207Z DEBUG drop{self=Environment { env: Mutex { data: EnvironmentSingleton { name: "Yolo", env_ptr: 0x148a05c2fc0 }, poisoned: false, .. }, execution_providers: [DirectML(DirectMLExecutionProviderOptions { device_id: 0 }), TensorRT(TensorRTExecutionProviderOptions { device_id: 0, max_workspace_size: 1073741824, max_partition_iterations: 1000, min_subgraph_size: 1, fp16_enable: true, int8_enable: false, int8_calibration_table_name: "", int8_use_native_calibration_table: false, dla_enable: true, dla_core: 0, engine_cache_enable: false, engine_cache_path: "", dump_subgraphs: false, force_sequential_engine_build: false, enable_context_memory_sharing: false, layer_norm_fp32_fallback: false, timing_cache_enable: true, force_timing_cache: false, detailed_build_log: false, enable_build_heuristics: false, enable_sparsity: false, builder_optimization_level: 3, auxiliary_streams: 0, tactic_sources: "", extra_plugin_lib_paths: "", profile_min_shapes: "", profile_max_shapes: "", profile_opt_shapes: "" }), CUDA(CUDAExecutionProviderOptions { device_id: 0, gpu_mem_limit: 18446744073709551615, arena_extend_strategy: NextPowerOfTwo, cudnn_conv_algo_search: Exhaustive, do_copy_in_default_stream: true, cudnn_conv_use_max_workspace: true, cudnn_conv1d_pad_to_nc1d: false, enable_cuda_graph: false, enable_skip_layer_norm_strict_mode: false })] }}: ort::environment: Dropping environment global_arc_count=2
2023-09-26T16:41:24.292221Z DEBUG drop{self=Environment { env: Mutex { data: EnvironmentSingleton { name: "Yolo", env_ptr: 0x148a05c2fc0 }, poisoned: false, .. }, execution_providers: [DirectML(DirectMLExecutionProviderOptions { device_id: 0 }), TensorRT(TensorRTExecutionProviderOptions { device_id: 0, max_workspace_size: 1073741824, max_partition_iterations: 1000, min_subgraph_size: 1, fp16_enable: true, int8_enable: false, int8_calibration_table_name: "", int8_use_native_calibration_table: false, dla_enable: true, dla_core: 0, engine_cache_enable: false, engine_cache_path: "", dump_subgraphs: false, force_sequential_engine_build: false, enable_context_memory_sharing: false, layer_norm_fp32_fallback: false, timing_cache_enable: true, force_timing_cache: false, detailed_build_log: false, enable_build_heuristics: false, enable_sparsity: false, builder_optimization_level: 3, auxiliary_streams: 0, tactic_sources: "", extra_plugin_lib_paths: "", profile_min_shapes: "", profile_max_shapes: "", profile_opt_shapes: "" }), CUDA(CUDAExecutionProviderOptions { device_id: 0, gpu_mem_limit: 18446744073709551615, arena_extend_strategy: NextPowerOfTwo, cudnn_conv_algo_search: Exhaustive, do_copy_in_default_stream: true, cudnn_conv_use_max_workspace: true, cudnn_conv1d_pad_to_nc1d: false, enable_cuda_graph: false, enable_skip_layer_norm_strict_mode: false })] }}: ort::environment: Releasing environment global_arc_count=2
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: CreateSession(Msg("Exception during initialization: "))', src\utils\act\onnx_detector.rs:141:61
stack backtrace:
   0:     0x7ff72835492c - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff72837affb - core::fmt::rt::Argument::fmt
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\fmt\rt.rs:138
   2:     0x7ff72837affb - core::fmt::write
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\fmt\mod.rs:1094
   3:     0x7ff72834fb39 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\io\mod.rs:1713
   4:     0x7ff7283546db - std::sys_common::backtrace::_print
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff7283546db - std::sys_common::backtrace::print
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff728357379 - std::panicking::default_hook::closure$1
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:269
   7:     0x7ff72835702f - std::panicking::default_hook
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:288
   8:     0x7ff72835787e - std::panicking::rust_panic_with_hook
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:705
   9:     0x7ff72835776d - std::panicking::begin_panic_handler::closure$0
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:597
  10:     0x7ff728355559 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\sys_common\backtrace.rs:151
  11:     0x7ff728357470 - std::panicking::begin_panic_handler
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\panicking.rs:593
  12:     0x7ff7283f6355 - core::panicking::panic_fmt
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\panicking.rs:67
  13:     0x7ff7283f6863 - core::result::unwrap_failed
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\core\src\result.rs:1651
  14:     0x7ff727e5ab4c - ambriel::utils::act::onnx_detector::OnnxDetector::detect::h8ef8adca5563c618
  15:     0x7ff727efe5d2 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h5397c2752673e612
  16:     0x7ff727f33774 - tauri::hooks::InvokeResolver<R>::respond_async_serialized::{{closure}}::h60a77915f2059010
  17:     0x7ff727f403e4 - tokio::runtime::task::core::Core<T,S>::poll::had9a5d74af1cf8fd
  18:     0x7ff727db5b28 - tokio::runtime::task::harness::Harness<T,S>::poll::he76b2716923eae46
  19:     0x7ff7282bd505 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hb5b9c3a8d2cd6dd6
  20:     0x7ff7282bc130 - tokio::runtime::scheduler::multi_thread::worker::Context::run::hb5b9c3a8d2cd6dd6
  21:     0x7ff72829af2e - tokio::runtime::context::scoped::Scoped<T>::set::hf07ff0012480616b
  22:     0x7ff7282ad8c1 - tokio::runtime::context::runtime::enter_runtime::h554e160fff3c8048
  23:     0x7ff7282bbfc7 - tokio::runtime::scheduler::multi_thread::worker::run::h8b6fc4457aafd20c
  24:     0x7ff728294a14 - tokio::runtime::task::core::Core<T,S>::poll::h710f53ee6fb404e7
  25:     0x7ff728297b20 - tokio::runtime::task::harness::Harness<T,S>::poll::hd7fd358e8f05819c
  26:     0x7ff7282b636b - tokio::runtime::blocking::pool::Inner::run::h46d5d912c5f18fe6
  27:     0x7ff7282998be - std::sys_common::backtrace::__rust_begin_short_backtrace::h1c13a104bb5d2b5c
  28:     0x7ff7282a3e18 - <&T as core::fmt::Debug>::fmt::h975393e78109dceb
  29:     0x7ff72836514c - std::sys::windows::thread::impl$0::new::thread_start
                               at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library\std\src\sys\windows\thread.rs:57
  30:     0x7ffa8a75257d - BaseThreadInitThunk
  31:     0x7ffa8b48aa78 - RtlUserThreadStart
```

**Comment by 18930215187** [comment]
https://drive.google.com/drive/folders/11BKzKklXBPYmIISyMHBX0GSD16ErJsRT?usp=drive_link

Here is my code and model

**Comment by decahedron1** [comment]
Quickly glancing at the model I don't see anything that should cause an issue with DirectML. Does the same model work in Python with `DmlExecutionProvider`? If so, this ONNX Runtime might be related: https://github.com/microsoft/onnxruntime/issues/13429#issuecomment-1292891636

**Comment by 18930215187** [comment]
@decahedron1 I'm sorry for late response. The DirectMl.dll existed in my ORT_LIB_LOCATION. I tried my model with python onnxruntime and the output is:
```
2 0 2 3 - 0 9 - 2 8   1 8 : 1 2 : 1 0 . 0 9 8 7 0 9 3   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 1 6 9   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   S o m e   n o d e s   w e r e   n o t   a s s i g n e d   t o   t h e   p r e f e r r e d   e x e c u t i o n   p r o v i d e r s   w h i c h   m a y   o r   m a y   n o t   h a v e   a n   n e g a t i v e   i m p a c t   o n   p e r f o r m a n c e .   e . g .   O R T   e x p l i c i t l y   a s s i g n s   s h a p e   r e l a t e d   o p s   t o   C P U   t o   i m p r o v e   p e r f . 
 2 0 2 3 - 0 9 - 2 8   1 8 : 1 2 : 1 0 . 0 9 8 8 7 8 0   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 1 7 1   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   R e r u n n i n g   w i t h   v e r b o s e   o u t p u t   o n   a   n o n - m i n i m a l   b u i l d   w i l l   s h o w   n o d e   a s s i g n m e n t s . 
```
I had build the wheel file for source with "Release" instead of "MinSizeRel", I look forword to receive the solution to this problem soon. Thank you very much.

**Comment by decahedron1** [comment]
> The DirectMl.dll existed in my ORT_LIB_LOCATION.

`DirectML.dll` needs to be placed next to your executable, it will not be picked up from `ORT_LIB_LOCATION`.

It's likely that your model is incompatible with both DirectML and TensorRT, in which case there's not really anything I can do on my side 😕
